name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  java_build:
    strategy:
      matrix:
        java_version: [ 8, 11, 17, 21 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with JDK ${{ matrix.java_version }}
        run: mvn -B clean test ${{ matrix.included_modules }}
        env:
          OPENAI_BASE_URL: 'http://langchain4j.dev:8082/v1'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}