name: release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        settings-path: ${{ github.workspace }}

    - name: release
      run: mvn -B clean deploy -Psign
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
